# Generated by Django 3.1.13 on 2021-10-14 17:07

import admin_async_upload.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=140)),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('is_displayable', models.BooleanField(default=True, help_text='Set to false when you need to not see in forms.', verbose_name='Displayable')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('body', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('owner', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='blog/headers/')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='Company name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('title', models.TextField()),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Url Field')),
                ('html_content', models.TextField(blank=True, null=True, verbose_name='Html Content')),
                ('audio_file', admin_async_upload.models.AsyncFileField(blank=True, null=True, upload_to='contents/audios')),
                ('subtitled', models.BooleanField(default=False, help_text='Set to true when content is subtitled.', verbose_name='Subtitled')),
                ('skip', models.BooleanField(default=False, verbose_name='Skip url validation')),
                ('copy', models.TextField(blank=True, null=True, verbose_name='Copy Content')),
                ('footer', models.TextField(blank=True, null=True, verbose_name='Footer Content')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Creation date content')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='contents.blog')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=150)),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=150)),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('route_issuer', models.CharField(max_length=150)),
                ('corporative', models.BooleanField(default=False, help_text='Set to true when the route is corporative.')),
                ('area', models.ForeignKey(help_text='Area for route.', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='contents.area')),
                ('company', models.ForeignKey(blank=True, help_text='Company for route.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='contents.company')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('position', models.PositiveIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_modules', to='contents.module')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_modules', to='contents.route')),
            ],
            options={
                'unique_together': {('route', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ContentModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('position', models.PositiveIntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_modules', to='contents.content')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_modules', to='contents.module')),
            ],
            options={
                'unique_together': {('module', 'position')},
            },
        ),
    ]
