# Generated by Django 3.1.13 on 2021-11-13 12:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20211028_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='copy',
            field=ckeditor.fields.RichTextField(default='hola'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='footer',
            field=ckeditor.fields.RichTextField(default='chao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='html_content',
            field=ckeditor.fields.RichTextField(default='wwww.html.com'),
            preserve_default=False,
        ),
    ]
